language: csharp
mono: none
dotnet: 2.1.300
env:
  global:
    - PGPORT=5433
  matrix:
    - DefaultConnection="Server=localhost; Database=datingapp; Username=postgres"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
services:
  - postgresql
before_script:
  - psql -l
  - psql -U postgres -c 'create database datingapp;'
script:
  - dotnet build
  - dotnet ef database update
notifications:
  email: false
