language: csharp
mono: none
dotnet: 2.1.300
env:
  - DefaultConnection="Server=localhost; Database=datingapp; Username=postgres"
addons:
  postgresql: "10.4"
services:
  - postgresql
before_script:
  - psql -c 'create database datingapp;' -U postgres
script:
  - dotnet build
  - dotnet ef database update
notifications:
  email: false
